<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DINA" ignored="0" name="Test" tests="2" failures="1" timestamp="23 Feb 2018 19:12:46 GMT" time="0.055" errors="0">
  <testcase name="dummy_test_to_fail" time="0.01" classname="Test.test">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]at Test.test.dummy_test_to_fail(test.java:16)... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- dummy_test_to_fail -->
  <testcase name="dummy_test_to_pass" time="0.0" classname="Test.test"/>
</testsuite> <!-- Test -->
